### PR TITLE
Added type definitions

### PR DESCRIPTION
**Pull request by Polarts**
I couldn't fine a more reliable and easy to use library for multi-finger gestures, so I chose this one which somehow works perfectly despite being 10 years old.
Since my project is in TypeScript, I had to map the types. Thought I might as well contribute, if you're still here and interested.

### CODE REVIEW

**Comment by paztis** [comment]
hi Good idea.

I totally stop working on it since long time.
Just add the type declaration in the package.json and I will approve it

**Comment by Polarts** [comment]
@paztis Done 😁

**Comment by paztis** [comment]
Merged

**Comment by paztis** [comment]
Merge

**Pull request merged**
